### ISSUE TITLE
Population fails on empty values

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers-hooks#137] opened 2017-02-19 09:38 UTC
I have a situation where in some cases the field I'm trying to populate doesn't alway have a value which results in the error

```
{
  "name": "BadRequest",
  "message": "ParentField product_offer for product_offer depth 1 is undefined. (populate)",
  "code": 400,
  "className": "bad-request",
  "errors": {}
}
```
To overcome this I'm currently having to put another hook before the populate to add a dummy field with a null value which then resolves the problem. 

Is this something that could be added to the populate hook?

**Comment by eddyystop** [comment] 2017-04-14 18:31
Looks like a duplicate of https://github.com/feathersjs/feathers-hooks-common/issues/138

Please reopen if you don't agree.

**Closed by eddyystop** 2017-04-14 18:31 UTC
Labels: enhancement
