### ISSUE TITLE
Unable to modify result object in after hook

### ISSUE THREAD

**Issue by startupthekid** [feathersjs/feathers-hooks#23] opened 2015-10-25 22:09 UTC
In the README, it states "In any after hook, only modifications to the result object will have any effect". I've noticed that when I do something like `hook.result = {}`, the data sent back to the client matches `{}` but when I do `hook.result.token = jwt.sign...`, not only does `hook.result.token` not print to the console with `console.log`, but the token never shows up in my response data. The same is true when I try `delete hook.result.password`, the password shows up in the final response.

In order to add a token, would I have to copy all the keys and values that I want to include into a new object and then add the new ones? Like so: `hook.result = {"id": "someID", "Token":"some_token"}`.

If that is the case, is it possible to change that? Being able to do `hook.result.some_property = ...` wouldn't break the invariant of "only modifications to the result object will have any effect" and it would help to keep the code inside hook functions to a bare minimum.

**Comment by daffl** [comment] 2015-10-25 22:38
You should be able to modify the result object. This is being tested right at https://github.com/feathersjs/feathers-hooks/blob/master/test/after.test.js#L8. Can you provide an example that doesn't work?

**Comment by startupthekid** [comment] 2015-10-25 22:47
Sure thing!

I have an `after` hook for the `create` method, where I want to insert a signed jwt token.
```
app.service('users').after({
		create: function(hook, next) {
			console.log('calling next');
			var options = {
				expiresIn: 60*20
			};
                        delete hook.result.password;
			hook.result.custom_object = {key: "hi there"};
			next(null, hook);
		}
	})
```

^Here I've deleted the password and added a custom dictionary object but in the response:

```
{
  "__v": 0,
  "email": "something@something.com",
  "_id": "562d5b401b37c5ab8ae3a3d6",
  "password": "$2a$10$et4FKtSSuqg6/YNTeLuU0euP.xF801NxpfhrTMn6ANE7QIT8jKyA."
}
```

**Comment by startupthekid** [comment] 2015-10-26 00:51
I did a little more investigating and I discovered that it is possible to modify values of the result object but only for keys that already exist.

For example, if I do `hook.result.password = 'poop'`, it works and comes back in the response as `poop`. But if I try to add a key or delete a key, that has no effect.

**Comment by daffl** [comment] 2015-10-26 01:20
Odd, I thought adding new properties is what the test case I linked is covering.
Can you try calling `next()` without any arguments (instead of `next(null, hook);` from your example) and see if that changes anything?

**Comment by marshallswain** [comment] 2015-10-26 05:17
I'm experiencing this same issue, but I don't have time to troubleshoot more tonight.  In an after hook, if I add a property or delete a property from `hook.result`, it makes no difference in the data, but if I set an existing property to undefined, it will remove that property in the output.  Changing from `next(null, hook) to `next()` made no difference.

**Comment by daffl** [comment] 2015-10-26 18:11
I can't verify this. The following app:

```js
var feathers = require('feathers');
var hooks = require('feathers-hooks');
var bodyParser = require('body-parser');

var app = feathers()
  .configure(feathers.rest())
  .use(bodyParser.json())
  .configure(hooks())
  .use('/todos', {
    create: function(data, params, callback) {
      callback(null, data);
    }
  });

app.service('todos').after({
  create: [function(hook ,next) {
    hook.result.test = 'hi';
    next();
  }, function(hook ,next) {
    hook.result.input = 'Modified input';
    next();
  }, function(hook ,next) {
    delete hook.result.password;
    next();
  }]
});

app.listen(4040);
```

seems to work fine. When sending a POST like

```js
{
  "input": "Test",
  "password": "bla"
}
```

It returns with

```js
{
    "input": "Modified input",
    "test": "hi"
}
```

Which is exactly what I'd expect.

**Comment by marshallswain** [comment] 2015-10-27 04:29
I tracked my problem down to the feathers-mongoose adapter.  It's returning
a mongoose model instance instead of a plain object.

**Comment by daffl** [comment] 2015-10-27 04:44
I remember someone else having that problem before. The adapter should really call `.toJSON()` or whatever Mongoose provides for serialization before passing it off. Can you create an issue? This shouldn't be a hard fix I imagine.

/cc @ekryski

**Comment by marshallswain** [comment] 2015-10-27 05:54
Yeah.  We need to call query.lean() before execution to save resources.

**Comment by ekryski** [comment] 2015-10-27 13:14
@marshallswain that works but I don't think it should be a blanket approach. You can also call `.toObject()` or `toJSON()` in an after hook.

I've run into this several times but returning a mongoose model is advantageous because it allows you to call instance/static/virtual methods which may aid in custom serialization. IMO for us to call `.lean()` on **all** mongoose queries kind of defeats the purposed of having an ORM adapter like mongoose in the first place.

With that said, at the very least this needs to be documented somewhere. Typically in my mongoose schema definition I'd end up having these options enabled:

```js
var PostSchema = new Schema({
      title: {type: String, trim: true, validate: validator.title},
      author: {type: Schema.ObjectId, ref: 'User', required: true, validate: validator.author},
      updatedAt: {type: Date, default: Date.now},
      createdAt: {type: Date, default: Date.now}
    },
    {
      toObject: {
        virtuals: true
      },
      toJSON: {
        virtuals: true
      }
    }
  );
```

and in an after hook I might have something like this:

```js
function serializePosts (hook, next) {
      if (hook.result) {
        var posts = hook.result;
        var serializedPosts = [];
        posts.forEach(function (post) {
          var newPost = post.toObject();

          newPost.author = {
            profileImageUrl: post.author.profileImageUrl,
            displayName: post.author.displayName
          };
          serializedPosts.push(newPost);
        });

        hook.result = serializedPosts;
     }

 next();
}
```

Definitely not ideal and I'd like to find a better way but I think just calling `.lean()`, `.toJSON()`, or `.toObject()` inside of the mongoose adapter is too restrictive because then there is no way to access your instance methods. Open to ideas.

**Comment by daffl** [comment] 2015-10-27 14:54
This is fine actually. It's only a problem when using hooks, so you might as well add a hook that does serialization first, kind of like

```
app.service('users').after({
  create: function(hook, next) {
    hook.result = hook.result.toObject();
    next();
  }
});
```

Which should solve all those problems. I was thinking last night if we might want to add useful hooks to the database adapters, for examples this one or a hook that counts all objects matching a query etc.

Either way, I think use with hooks needs to be documented in feathers-mongoose and then we can probably close this issue (@startupthekid unless this doesn't solve your problem).

**Comment by marshallswain** [comment] 2015-10-27 15:15
I agree.  This is a hooks-related issue, and bundled hooks is a great solution.

**Comment by ekryski** [comment] 2015-10-27 15:39
@daffl :+1: for docs. I'll add it later today.

On the fence about bundled hooks. Wondering how they would be accessed within an app. I've had a thought for a while that we might have a repo that contains common hooks. Especially for validations, password removal, createdAt, updatedAt, etc.

**Comment by daffl** [comment] 2015-10-27 15:51
Yes, was talking about that with @marshallswain, too. But I think some do belong into the DB adapters though. For example, counting the results of a query or serializing a Mongoose model is pretty specific to the adapter.

**Comment by startupthekid** [comment] 2015-10-27 18:52
@daffl this should solve what I was seeing. I later realized exactly what ya'll are saying, the the mongoose service wrapper was returning a mongoose object instead of the result of `model.toObject()`. Adding a hook to do that transformation seems like a great solution to me, because there definitely are instances where I want the mongoose properties and others where I don't.
Thanks for the quick responses dudes. :+1:

**Comment by ekryski** [comment] 2015-10-27 19:47
@startupthekid :+1: 

@daffl ok I'm sold. How do you think they should be required? I guess if we convert to ES6 just:

```js
import hooks from 'feathers-mongoose';
```

**Comment by daffl** [comment] 2015-10-28 01:40
@ekryski probably

```js
import { hooks } from 'feathers-mongoose';
// or
import { hooks as mongooseHooks } from 'feathers-mongoose';
```

I created a related issue at https://github.com/feathersjs/feathers-mongoose/issues/25. Closing this issue since we found the cause (and it is not really an issue with this plugin)

**Closed by daffl** 2015-10-28 01:40 UTC

**Comment by itoonx** [comment] 2017-03-19 16:13
thanks so much, this is safe my day
